spring:
  application:
    name: OnlineOrder

  datasource:
    url: jdbc:postgresql://${DB_HOST:${DATABASE_URL:localhost}}:${DB_PORT:${DATABASE_PORT:5432}}/${DB_NAME:${DATABASE_NAME:onlineorder}}

    username: ${DB_USERNAME:${DATABASE_USERNAME:postgres}}

    password: ${DB_PASSWORD:${DATABASE_PASSWORD:secret}}

    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:always}

      schema-locations: classpath:database-init.sql

  jackson:
    default-property-inclusion: non_null

    property-naming-strategy: SNAKE_CASE

  cache:
    caffeine:
      spec: expireAfterWrite=60s

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: INFO

    org.springframework.jdbc.datasource.init: DEBUG

    org.springframework.jdbc.core: DEBUG

    org.springframework.web: DEBUG
